// import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import Script from 'next/script';
import { Footer } from '../../library/components/Footer';
import { Navbar } from '../../library/components/Navbar';
import { menu } from '../data/menu';
import './globals.css';

// const inter = Inter({ subsets: ['latin'] });

// TODO check that Inter is loaded on browser that doesn't support variable fonts
const interVariable = localFont({
    display: 'swap',
    src: [
        {
            path: '../fonts/InterVariable-Italic.woff2',
            style: 'italic',
        },
        {
            path: '../fonts/InterVariable.woff2',
            style: 'normal',
        },
    ],
});

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="fr"
            className={`${interVariable.className} antialiased`}
        // className={`${inter.className} ${interVariable.className} antialiased`}
        >
            <body>
                <div className="background-color-mask">
                    <Navbar menuItems={menu} />
                    {children}
                    <Footer />
                    <Script src="vanilla-tilt.js" />
                </div>
            </body>
        </html>
    );
}
