import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import { Footer } from '../../library/components/Footer';
import { Navbar } from '../../library/components/Navbar';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

// TODO check that Inter is loaded on browser that doesn't support variable fonts
const interVariable = localFont({
    display: 'swap',
    src: [
        {
            path: '../fonts/InterVariable-Italic.woff2',
            style: 'italic',
        },
        {
            path: '../fonts/InterVariable.woff2',
            style: 'normal',
        },
    ],
});

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="fr"
            className={`${inter.className} ${interVariable.className} antialiased`}
        >
            {/* <QueryClientProvider client={queryClient}> */}
            {/* <SettingsProvider> */}
            {/* <Providers> */}
            {/* <ThemeProviderMUI theme={muiTheme}> */}
            {/* <ThemeProvider theme={mergeObjects(themeBase, currentTheme)}> */}
            <body>
                <div className="background-color-mask">
                    <Navbar />
                    {children}
                    <Footer />
                    <script
                        type="text/javascript"
                        src="vanilla-tilt.js"
                        async
                        defer
                    ></script>
                </div>
            </body>
            {/* </ThemeProvider> */}
            {/* </ThemeProviderMUI> */}
            {/* </Providers> */}
            {/* </SettingsProvider> */}
            {/* </QueryClientProvider> */}
        </html>
    );
}
